from typing import Any, Optional

def Lucide(name: str = None, cls: Optional[str] = None, size: Optional[str] = '24', color: Optional[str] = 'currentColor', stroke_width: Optional[str] = '2', absolute_sw: Optional[bool] = False, **kwargs: Any): ...